2020-08-28 14:55:28,486 ERROR: Exception on /index [GET] [in /Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/macbook/lang/flask_web_app/app/routes.py", line 19, in index
    newsapi = NEWSAPI.get_top_headlines(country=language)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/newsapi/newsapi_client.py", line 130, in get_top_headlines
    raise ValueError("invalid country")
ValueError: invalid country
2020-08-28 14:56:04,035 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-28 14:56:26,016 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-28 14:58:05,893 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-28 14:58:09,149 ERROR: Exception on /index [GET] [in /Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/macbook/lang/flask_web_app/app/routes.py", line 20, in index
    newsapi = NEWSAPI.get_top_headlines(country=language)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/newsapi/newsapi_client.py", line 130, in get_top_headlines
    raise ValueError("invalid country")
ValueError: invalid country
2020-08-28 14:58:30,834 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-28 14:58:33,486 ERROR: Exception on /index [GET] [in /Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/macbook/lang/flask_web_app/app/routes.py", line 20, in index
    newsapi = NEWSAPI.get_top_headlines(country=language)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/newsapi/newsapi_client.py", line 130, in get_top_headlines
    raise ValueError("invalid country")
ValueError: invalid country
2020-09-01 12:04:53,240 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 12:05:05,978 ERROR: Exception on /index [GET] [in /Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/macbook/lang/flask_web_app/app/routes.py", line 20, in index
    newsapi = NEWSAPI.get_top_headlines(country)
NameError: name 'country' is not defined
2020-09-01 12:06:19,293 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 12:06:23,418 ERROR: Exception on /index [GET] [in /Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/macbook/lang/flask_web_app/app/routes.py", line 20, in index
    newsapi = NEWSAPI.get_top_headlines(country="uk")
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/newsapi/newsapi_client.py", line 130, in get_top_headlines
    raise ValueError("invalid country")
ValueError: invalid country
2020-09-01 12:06:53,753 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 12:26:33,800 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 12:28:38,108 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 12:56:35,723 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 12:56:39,492 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 12:57:08,248 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 12:57:33,066 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 12:59:33,319 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-01 13:00:14,765 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-03 00:16:36,781 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-03 00:24:53,734 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-09-03 00:40:31,701 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
